### ISSUE TITLE
epic(Recipes): change relation between models and recipes

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#1111]
### Epic domain

Today, when importing a new models, it cannot be used in recipes. This issue come from the fact that we are hardcoding the compatible models in the recipe definition.

## Introducing `backend` field

- [x] #1181
- [x] #1192
- [x] #1195

## Recipes should have a `recommended` field

- [ ] Recipes could recommend the best suitable models (plural)
- [ ] Recipe details page highlight the recommended model(s)

## Catalog migration

- [ ] Catalog should be versioned 
- [ ] We should handle catalog migration

**Comment by axel7083** [comment]
Closing as completed
