### ISSUE TITLE
epic: enabling GPU

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#1143]
### Epic domain

We need an issue to keep track of the requirements to support the GPUs in AI Lab

- [ ]: Detecting GPU(s) on Windows (Name, VRAM) 
- [ ]: Detecting GPU(s) on Mac (Name, VRAM) 
- [ ]: Detecting GPU(s) on Linux (Name, VRAM)

**Comment by axel7083** [comment]
List of issues encountered on windows

## ulimit problems

```
warning: failed to mlock 74489856-byte buffer (after previously locking 0 bytes): Cannot allocate memory
Try increasing RLIMIT_MEMLOCK ('ulimit -l' as root).
```

Solution: prefix `export use_mlock=False` before starting the llamacpp server

ref: https://github.com/abetlen/llama-cpp-python/issues/708

## Root requirement with the WSL

Need to run the container with `--user 0` to let it access properly the GPU
