### ISSUE TITLE
Playground Scenario QE Coverage

### ISSUE THREAD

**Issue by odockal** [containers/podman-desktop-extension-ai-lab#2249]
### Epic domain

Test automation should cover the most used models and playground functionality. The E2E test scenario should cover at least happy path and use the most used models from ai-lab offering.

### Additional context

* [ ] https://github.com/containers/podman-desktop-extension-ai-lab/issues/2101
* [ ] smoke test run on windows and mac in an automated way
* [ ] scenario cover the most used models
* [ ] scenario is stable
