### ISSUE TITLE
feat: PlaygroundV2

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#535]
With the `InferenceManager` the playground do not need to handle all the container lifecycle, nor the events it can occurs. It can simply get the InfernceServers available, check if healthy, get the port, and make request on it. 

The UI should be responsible of creating/start an inference server if there is none running/stopped.

We have two concept, the `Conversation` and `Playground`. 

### Conversation

We want a dedicated page for the conversation history accessible from the navigation bar. The conversation (post 0.3) should persistent, they need to be stored locally. 

One conversation is holding several messages, model options used, timestamps, (etc?.)

- [ ] Designing a Conversation interface
- [ ] Creating a `ConversationManager`
- [ ] Creating a Conversation store for the frontend
- [ ] Creating a conversation history page

### Playground

The playground should be simple, (almost stateless), when submitting a message it should take as argument conversation id, user input and model options (E.g. modeId, temperature...).

- [x] https://github.com/projectatomic/ai-studio/issues/509
- [x] https://github.com/projectatomic/ai-studio/issues/543
- [ ] Cleanup Playground v1 code (remove classes, apis, ui)

cc @jeffmaury @feloy
