### ISSUE TITLE
epic(snippets): write code snippets

### ISSUE THREAD

**Issue by axel7083** [containers/podman-desktop-extension-ai-lab#607]
- [ ] Generating the code snippets
     - [x] https://github.com/projectatomic/ai-studio/issues/408
     - [x] https://github.com/projectatomic/ai-studio/issues/407
     - [x] https://github.com/projectatomic/ai-studio/issues/406
     - [x] https://github.com/projectatomic/ai-studio/issues/405 
     - [x] https://github.com/projectatomic/ai-studio/issues/404
     - [x] https://github.com/projectatomic/ai-studio/issues/403 (priority)

**Comment by lstocchi** [comment]
I think we can close this. All tasks are completed
