### ISSUE TITLE
AI Studio extension QE coverage - part 2

### ISSUE THREAD

**Issue by ScrewTSW** [containers/podman-desktop-extension-ai-lab#793]
Follow-up containers/podman-desktop-internal/issues/172

### Epic domain

Implement AI Studio extension build from source, extend existing test with extension interaction, demo application deployment and verification

## Consists of multiple steps

* [x] Modify workflow to do extension build from source
* [x] [Extend existing playwright scenario with handling Extension webview content](https://github.com/containers/podman-desktop-extension-ai-lab/issues/978)
* [x] [Extend basic smoke test to verify AI App demo scenario](https://github.com/containers/podman-desktop-extension-ai-lab/issues/978)
* [x] [E2E Tests are being run on Mac platform on nightly base](https://github.com/containers/podman-desktop-e2e/issues/201)
